import type { Metadata } from "next";
import { Karla } from "next/font/google";
import "./globals.css";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import DesktopNav from "@/components/layouts/desktop-nav";
import Footer from "@/components/page-components/home-page/footer";

const karla = Karla({ weight: ["400", "500", "700", "800"], subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={karla.className}>
        <DesktopNav />
        {children}
        <Footer />
      </body>
    </html>
  );
}
